Add unit tests
Diffblue-benchmarks/vjtools pull request #1
Opened 2018-11-14 13:41 UTC by louismillsdiffblue

Hi,

I've analysed your codebase and produced some unit tests for the following classes - Formats and Utils

I've written the tests for these functions with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/s/Diffblue-Cover-Datasheet.pdf).

Hopefully, these tests should help you detect regressions caused by future code changes.

2018-11-14 14:03 UTC, James-Adam commented on vjtop/pom.xml
> +            <groupId>com.diffblue</groupId>
Looks like we don't need to pull in Deeptestutils for this project.

2018-11-14 15:38 UTC, James-Adam commented on vjtop/src/test/java/com/vip/vjtools/vjtop/util/FormatsTest.java
> +}
Add a newline here :+1:

2018-11-14 15:40 UTC, sudo-jaa approved these changes

2018-11-14 15:50 UTC, petersear requested changes

2018-11-14 15:50 UTC, petersear commented on vjtop/src/test/java/com/vip/vjtools/vjtop/util/FormatsTest.java
> +
Remove one blank line

2018-11-14 15:50 UTC, petersear commented on vjtop/src/test/java/com/vip/vjtools/vjtop/util/FormatsTest.java
> +
Remove one blank line

2018-11-14 16:12 UTC, petersear approved these changes

2018-11-14 16:58 UTC, paulkennethkent approved these changes

2018-11-22 09:17 UTC, JohnLBergqvist requested changes
Your commit messages must be in the following format (commit messages can be multi-line):
```
Add unit tests for <class>
These tests were written by Diffblue Cover.
Dependencies required to run the tests have also been added.
```

Secondly, the title of the PR should contain the classes you are modifying, or at least be like this:
`Add unit tests for com.vip.vjtools.vjtop.util`

2019-04-18 13:16 UTC, merged